#!/bin/bash

# Assumes all commits have been synchronized to https://github.com/ruby/spec
# See spec/mspec/tool/sync/sync-rubyspec.rb

update() {
    rm -rf "spec/$1"
    git clone --depth 1 "https://github.com/ruby/${2-$1}.git" "spec/$1"
    commit=$(git -C "spec/$1" log -n 1 --format='%h')
    rm -rf "spec/$1/.git"
    git add "spec/$1"
    git commit -m "Update to ruby/${2-$1}@${commit}"
}

update mspec
update ruby spec
